name: "taskbees-backend"

type: "nodejs:18"  # Node.js 18

disk: 1024

hooks:
    build: |
        npm install --force
        npm run build

relationships: {}
     # Match this with the service name defined in .platform/services.yaml

web:
    commands:
        start: npm run start:prod
    locations:
        "/":
            root: ""
            passthru: true

mounts:
    "node_modules/":
        source: local
    "uploads/":
        source: local

variables:
    env:
        # NODE_ENV: "production"
        # APP_PORT: 8085
        # APP_NAME:  TASK BEES
        # APP_DESCRIPTION: Task Bees Backend
        # API_PREFIX: api
        # APP_VERSION:  1.0.0
        # BACKEND_DOMAIN:  http://127.0.0.1:8085
        # TYPEORM_CONNECTION: postgres
        # TYPEORM_URL: postgresql://neondb_owner:1Uau2qCzWijk@ep-rapid-grass-a5xl5buu.us-east-2.aws.neon.tech/neondb?sslmode:require
        # TYPEORM_ENTITIES: src/modules/**/*entity.ts
        # TYPEORM_ENTITIES_DIR : src/database/entities
        # TYPEORM_MIGRATIONS : src/database/migrations/**/*.ts
        # TYPEORM_MIGRATIONS_DIR : src/database/migrations
        # TYPEORM_SEEDING_FACTORIES : src/database/factories/**/*.ts
        # TYPEORM_SEEDING_SEEDS : src/database/seeds/**/*.ts
        # TYPEORM_SYNCHRONIZE : true
        # TYPEORM_LOGGING : false
        # TYPEORM_AUTOLOAD : true
        # CACHING_DURATION : 14400000
        # CACHING_KEY_JOBS : all_jobs
        # CACHING_KEY_EVENTS : all_events
        # CACHING_KEY_CATEGORIES : all_categories
        # CACHING_KEY_TAGS : all_tags
        # CACHING_KEY_TYPES : all_types
        # CACHING_KEY_BUSINESS: all_businesses
        # BING_MAPS_API_KEY : AmNN4Ad_mq7vvX4Mh_1Q7ZsyMrZeHsacNcaSyECNUswgJoN1oFY6lTQDMXGuAsCC
        # REDIS_PASSWORD : CatmN4hCjFRBSoSyGo6k1Q5xOJsxUGu7
        # REDIS_HOST : redis-11340.c16.us-east-1-3.ec2.redns.redis-cloud.com
        # REDIS_PORT : 11340
        # MEASUREMENT_ID : G-9TXSP7DZ7N
        # JWT_ACCESS_TOKEN_SECRET_KEY : 2cf3543db29350706897c37a1cd1381134cea139fe5e50f3908304df46d0
        # ACCESS_TOKEN_EXPIRE : 20m # 20 minutes
        # JWT_REFRESH_TOKEN_SECRET_KEY : 972701cfde55256c219b579ea2b22cacbfd5e1d51f7b8e770f2949b59dd3
        # REFRESH_TOKEN_EXPIRE : 30d # 30 days
        # JWT_COMMON_SECRET_KEY : 2cf3543db29350706897c37a1cd1381134cea139fe5e50f3908304df46d0
        # EMAIL_ADDRESS : mosesmanek7@gmail.com
        # EMAIL_PASSWORD : ahjbylcdcxqyjwxo
        # EMAIL_FROM_NAME : moses maned
        # CLOUDINARY_NAME: dfiagonwj
        # CLOUDINARY_API_KEY: 941386628933121
        # CLOUDINARY_SECRET_KEY: fCTuyTeyqXpb5k1wuSPAVxV33aU
        # IS_DEV : true




